# Generated by Django 5.1.2 on 2024-10-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tags',
            new_name='tags',
        ),
    ]
